id = 0
[router]
dir = "config/rumqttd"
max_connections = 10000
max_outgoing_packet_count = 200
max_segment_size = 1048576
max_segment_count = 10

[console]
listen = "0.0.0.0:3030"

[metrics]
[metrics.alerts]
push_interval = 1
[metrics.meters]
push_interval = 1
[v4.1]
name = "tcp-internal"
listen = "0.0.0.0:1883"
next_connection_delay_ms = 1
[v4.1.connections]
connection_timeout_ms = 10000
max_client_id_len = 256
throttle_delay_ms = 0
max_payload_size = 5120
max_inflight_count = 100
max_inflight_size = 1024

[ws.1]
name = "ws-dashboard"
listen = "0.0.0.0:8083"
next_connection_delay_ms = 1
[ws.1.connections]
connection_timeout_ms = 10000
max_client_id_len = 256
throttle_delay_ms = 0
max_payload_size = 5120
max_inflight_count = 100
max_inflight_size = 1024

[ws.2]
name = "wss-dashboard"
listen = "0.0.0.0:8084"
next_connection_delay_ms = 1
[ws.2.connections]
connection_timeout_ms = 10000
max_client_id_len = 256
throttle_delay_ms = 0
max_payload_size = 5120
max_inflight_count = 100
max_inflight_size = 1024
[ws.2.tls]
capath = "config/cert.pem"
certpath = "config/cert.pem"
keypath = "config/key.pem"
